#!/usr/bin/env Rscript

# =============================================================================
# Step 2 (Chromosome+Plasmid overlay): PCoA Plotting by Host and Gene Type
# Description:
#   - Read PCoA coordinates generated by 213_step1_pcoa_chro_plas.R.
#   - For each gene type (defense, amr, antidefense) and each host plant
#     (Alfalfa, Rice, Wheat, Maize), create one PCoA plot.
#   - In each plot:
#       * Each point is one Sample_ID × Contig_Type3 (Plasmid / Chromosome).
#       * Color encodes bacterial class (e.g., Class_CRBC).
#       * Shape encodes contig type (Plasmid vs Chromosome).
#   - Chromosome and plasmid are always shown in the same panel for each host.
#
# Usage:
#   Rscript 214_step2_pcoa_chro_plas.R \
#       [-c <color_by>]
#
# Examples:
#   # Automatically scan all plas_chro_coordinates directories
#   # under the current working directory:
#   Rscript 214_step2_pcoa_chro_plas.R
#
# Arguments:
#   -c / --color-by     : Column used for color (default: Class_CRBC).
#
# Output naming:
#   For each input coordinates file:
#     <prefix>_coordinates.csv
#   output files are:
#     <prefix>_<Host>.pdf
#
# Notes:
#   - All code and comments are written in English.
#   - No envfit arrows are drawn here; only points are plotted.
# =============================================================================

suppressPackageStartupMessages({
  library(ggplot2)
  library(dplyr)
  library(argparse)
})

# ------------------------- 1. Parse arguments ------------------------------- #

parser <- ArgumentParser(
  description = "Create host-level PCoA plots with chromosome+plasmid overlay from all coordinates files."
)
parser$add_argument(
  "-c", "--color-by",
  default = "Class_CRBC",
  help = "Column name used for point color (default: Class_CRBC)."
)

args <- parser$parse_args()

# ------------------------- 2. Resolve directories --------------------------- #

find_coord_dirs <- function(root_dir = ".") {
  all_dirs <- list.dirs(path = root_dir, recursive = TRUE, full.names = TRUE)
  coord_dirs <- all_dirs[basename(all_dirs) == "plas_chro_coordinates"]
  unique(coord_dirs)
}

coord_dirs <- find_coord_dirs(".")

if (length(coord_dirs) == 0) {
  stop("No 'plas_chro_coordinates' directory was found under current working directory.")
}

cat("=== Step 2 (Chromosome+Plasmid overlay): Batch PCoA Plotting ===\n\n")
cat(sprintf("Working directory: %s\n", normalizePath(".", mustWork = TRUE)))
cat(sprintf("Found coordinate directories: %d\n", length(coord_dirs)))
cat(sprintf("Color by: %s\n\n", args$color_by))

# ------------------------- 3. Configuration -------------------------------- #

gene_labels <- c(
  defense     = "Defense Systems",
  amr         = "AMR Types",
  antidefense = "Anti-Defense Systems"
)

host_levels_target <- c("Alfalfa", "Rice", "Wheat", "Maize")

contig_shapes <- c(
  "Chromosome" = 16,  # solid circle
  "Plasmid"    = 2    # hollow triangle
)

# Color palette for bacterial classes (can be expanded if needed)
class_colors <- c(
  "Actinomycetia"        = "#98df8a",
  "Alphaproteobacteria"  = "#aec7e8",
  "Bacilli"              = "#ff7f0e",
  "Thermoleophilia"      = "#ff9896",
  "Bacteroidia"          = "#d62728",
  "Gammaproteobacteria"  = "#ffbb78",
  "Deinococci"           = "#1f77b4",
  "Acidimicrobiia"       = "#2ca02c",
  "Campylobacteria"      = "#9467bd"
)

generate_colors <- function(categories) {
  n <- length(categories)

  # If subset of predefined classes
  if (all(categories %in% names(class_colors))) {
    return(class_colors[categories])
  }

  # Otherwise, generate a larger palette
  if (n <= 12) {
    colors <- c(
      "#8dd3c7", "#ffffb3", "#bebada", "#fb8072",
      "#80b1d3", "#fdb462", "#b3de69", "#fccde5",
      "#d9d9d9", "#bc80bd", "#ccebc5", "#ffed6f"
    )
  } else {
    colors <- c(
      "#8dd3c7", "#ffffb3", "#bebada", "#fb8072", "#80b1d3", "#fdb462",
      "#b3de69", "#fccde5", "#d9d9d9", "#bc80bd", "#ccebc5", "#ffed6f",
      "#a6cee3", "#1f78b4", "#b2df8a", "#33a02c", "#fb9a99", "#e31a1c",
      "#fdbf6f", "#ff7f00", "#cab2d6", "#6a3d9a", "#ffff99", "#b15928"
    )
  }

  return(setNames(colors[seq_len(n)], categories))
}

# ------------------------- 4. Helper: read data ----------------------------- #

extract_type_from_prefix <- function(prefix_stem) {
  if (grepl("_defense$", prefix_stem)) return("defense")
  if (grepl("_amr$", prefix_stem)) return("amr")
  if (grepl("_antidefense$", prefix_stem)) return("antidefense")
  return("unknown")
}

read_one_prefix_data <- function(coord_file, var_file) {
  coords <- read.csv(coord_file, stringsAsFactors = FALSE)

  var_axis1 <- NA_real_
  var_axis2 <- NA_real_
  if (file.exists(var_file)) {
    var_df <- read.csv(var_file, stringsAsFactors = FALSE)
    if (nrow(var_df) >= 2) {
      var_axis1 <- var_df$Variance_Explained_Pct[1]
      var_axis2 <- var_df$Variance_Explained_Pct[2]
    } else if (nrow(var_df) >= 1) {
      var_axis1 <- var_df$Variance_Explained_Pct[1]
    }
  }

  list(
    coords = coords,
    var1 = var_axis1,
    var2 = var_axis2
  )
}

# ------------------------- 5. Plotting function ----------------------------- #

create_host_plot <- function(type_name, type_label, host_name, data_type, out_file) {
  df <- data_type$coords

  if (!all(c("PCoA1", "PCoA2", "Host", "Contig_Type3") %in% colnames(df))) {
    cat(sprintf("  [Warning] Missing required columns for type '%s'. Skipping host '%s'.\n",
                type_name, host_name))
    return(NULL)
  }

  df_host <- df %>%
    filter(Host == host_name)

  if (nrow(df_host) < 3) {
    cat(sprintf("  [Info] Host '%s', type '%s': fewer than 3 points. Skipping.\n",
                host_name, type_name))
    return(NULL)
  }

  # Drop rows with missing coordinates
  df_host <- df_host %>%
    filter(!is.na(PCoA1) & !is.na(PCoA2))

  if (nrow(df_host) < 3) {
    cat(sprintf("  [Info] Host '%s', type '%s': insufficient non-NA points after filtering.\n",
                host_name, type_name))
    return(NULL)
  }

  # Prepare color palette
  color_var <- args$color_by
  if (!color_var %in% colnames(df_host)) {
    cat(sprintf("  [Warning] Color variable '%s' not found. Using Host instead.\n", color_var))
    color_var <- "Host"
  }

  categories <- sort(unique(df_host[[color_var]][!is.na(df_host[[color_var]])]))
  color_palette <- generate_colors(categories)

  # Axis ranges and padding
  x_range <- range(df_host$PCoA1)
  y_range <- range(df_host$PCoA2)
  x_pad <- diff(x_range) * 0.15
  y_pad <- diff(y_range) * 0.15
  if (x_pad == 0) x_pad <- 0.5
  if (y_pad == 0) y_pad <- 0.5
  x_limits <- c(x_range[1] - x_pad, x_range[2] + x_pad)
  y_limits <- c(y_range[1] - y_pad, y_range[2] + y_pad)

  # Build plot
  p <- ggplot(
    df_host,
    aes_string(
      x = "PCoA1",
      y = "PCoA2",
      color = color_var,
      shape = "Contig_Type3"
    )
  ) +
    geom_point(alpha = 0.7, size = 2.8) +
    scale_color_manual(values = color_palette, name = gsub("_CRBC", "", color_var)) +
    scale_shape_manual(values = contig_shapes, name = "Contig type") +
    coord_cartesian(xlim = x_limits, ylim = y_limits) +
    theme_bw() +
    theme(
      plot.title = element_text(size = 14, face = "bold"),
      plot.subtitle = element_text(size = 10),
      legend.position = "right",
      legend.text = element_text(size = 9),
      legend.title = element_text(size = 10, face = "bold"),
      axis.title = element_text(size = 11),
      axis.text = element_text(size = 9),
      panel.grid.minor = element_blank()
    )

  subtitle_text <- sprintf(
    "Host: %s | Axis1: %.2f%%, Axis2: %.2f%% | n = %d points",
    host_name,
    data_type$var1,
    data_type$var2,
    nrow(df_host)
  )

  p <- p +
    labs(
      title = sprintf("PCoA of %s", type_label),
      subtitle = subtitle_text,
      x = sprintf("PCoA1 (%.2f%%)", data_type$var1),
      y = sprintf("PCoA2 (%.2f%%)", data_type$var2)
    )

  ggsave(out_file, p, width = 8, height = 6)
  cat(sprintf("  Plot saved: %s\n", out_file))

  return(p)
}

# ------------------------- 6. Main loop ------------------------------------ #

all_plots <- list()

for (coord_dir in coord_dirs) {
  base_dir <- dirname(coord_dir)
  var_dir <- file.path(base_dir, "plas_chro_variance")
  plots_dir <- file.path(base_dir, "plas_chro_plots")
  if (!dir.exists(plots_dir)) {
    dir.create(plots_dir, recursive = TRUE)
  }

  coord_files <- list.files(coord_dir, pattern = "_coordinates\\.csv$", full.names = TRUE)
  if (length(coord_files) == 0) {
    cat(sprintf("[Info] No coordinates files in: %s\n", coord_dir))
    next
  }

  cat("------------------------------------------------------------\n")
  cat(sprintf("Processing directory: %s\n", coord_dir))
  cat(sprintf("Variance directory : %s\n", var_dir))
  cat(sprintf("Plots directory    : %s\n", plots_dir))
  cat(sprintf("Coordinates files  : %d\n", length(coord_files)))
  cat("------------------------------------------------------------\n")

  for (coord_file in coord_files) {
    prefix_stem <- sub("_coordinates\\.csv$", "", basename(coord_file))
    type_name <- extract_type_from_prefix(prefix_stem)
    type_label <- ifelse(type_name %in% names(gene_labels), gene_labels[[type_name]], prefix_stem)
    var_file <- file.path(var_dir, sprintf("%s_variance.csv", prefix_stem))

    cat(sprintf("Processing prefix: %s\n", prefix_stem))
    data_type <- read_one_prefix_data(coord_file, var_file)

    if (!"Host" %in% colnames(data_type$coords)) {
      cat("  [Warning] Column 'Host' not found in coordinates. Skipping this prefix.\n")
      next
    }

    hosts_present <- intersect(host_levels_target, unique(data_type$coords$Host))

    if (length(hosts_present) == 0) {
      cat("  [Info] None of the target hosts (Alfalfa, Rice, Wheat, Maize) present. Skipping this prefix.\n")
      next
    }

    all_plots[[prefix_stem]] <- list()
    for (host_name in hosts_present) {
      host_safe <- gsub("[^A-Za-z0-9]+", "_", host_name)
      out_file <- file.path(plots_dir, sprintf("%s_%s.pdf", prefix_stem, host_safe))
      p <- create_host_plot(type_name, type_label, host_name, data_type, out_file)
      all_plots[[prefix_stem]][[host_name]] <- p
    }
  }
}

cat("\n=================================================================\n")
cat("PCoA plotting for chromosome+plasmid overlay design complete.\n")
cat("=================================================================\n")
cat(sprintf("\nAll plots were written to: %s\n", plots_dir))

